/*********** Mutations ***********/
// topics
export const FETCH_TOPICS_REQ = 'FETCH_TOPICS_REQ'
export const FETCH_TOPICS_SUC = 'FETCH_TOPICS_SUC'
export const FETCH_TOPICS_ERR = 'FETCH_TOPICS_ERR'
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA'
export const TOGGLE_NO_MORE_DATA_STATE = 'TOGGLE_NO_MORE_DATA_STATE'
export const TOGGLE_ERROR_DATA_STATE = 'TOGGLE_ERROR_DATA_STATE'
export const TOGGLE_ISFETCHING_STATE = 'TOGGLE_ISFETCHING_STATE'

export const FETCH_ACTIVITY_DATE_REQ = 'FETCH_ACTIVITY_DATE_REQ'
export const FETCH_ACTIVITY_DATE_SUC = 'FETCH_ACTIVITY_DATE_SUC'
export const FETCH_ACTIVITY_DATE_ERR = 'FETCH_ACTIVITY_DATE_ERR'
export const CLEAR_ACTIVITY_DATE_DATA = 'CLEAR_ACTIVITY_DATE_DATA'

// login
export const FETCH_USER_REQ = 'FETCH_USER_REQ'
export const FETCH_USER_SUC = 'FETCH_USER_SUC'
export const FETCH_USER_ERR = 'FETCH_USER_ERR'
export const COMMIT_USERINFO = 'COMMIT_USERINFO'
export const LOGOUT = 'LOGOUT'

// -----
// info page
export const FETCH_INFO_REQ = 'FETCH_INFO_REQ'
export const FETCH_INFO_SUC = 'FETCH_INFO_SUC'
export const FETCH_INFO_ERR = 'FETCH_INFO_ERR'
export const COMMIT_ID = 'COMMIT_ID'
export const TOGGLE_INFO_PAGE_DISPLAY = 'TOGGLE_INFO_PAGE_DISPLAY'
export const CLEAR_INFO_DATA = 'CLEAR_INFO_DATA'

// replies page
export const SHOW_REPLIES_PAGE = 'SHOW_REPLIES_PAGE'
export const HIDE_REPLIES_PAGE = 'HIDE_REPLIES_PAGE'
export const SHOW_COMMENT_BAR = 'SHOW_COMMENT_BAR'
export const HIDE_COMMENT_BAR = 'HIDE_COMMENT_BAR'
export const SEND_COMMENT_REQ = 'SEND_COMMENT_REQ'
export const SEND_COMMENT_SUC = 'SEND_COMMENT_SUC'
export const SEND_COMMENT_ERR = 'SEND_COMMENT_ERR'

// collect
export const SUC_COLLECT = 'SUC_COLLECT'
export const DEL_COLLECTED = 'DEL_COLLECTED'
	// -----

// message
export const FETCH_MSG_REQ = 'FETCH_MSG_REQ'
export const FETCH_MSG_SUC = 'FETCH_MSG_SUC'
export const FETCH_MSG_ERR = 'FETCH_MSG_ERR'
export const CLEAR_MSG_DATA = 'CLEAR_MSG_DATA'
export const FETCH_MARK_ALL_REQ = 'FETCH_MARK_ALL_REQ'
export const FETCH_MARK_ALL_SUC = 'FETCH_MARK_ALL_SUC'
export const FETCH_MARK_ALL_ERR = 'FETCH_MARK_ALL_ERR'

// messageList
export const FETCH_MSG_LIST_REQ = 'FETCH_MSG_LIST_REQ'
export const FETCH_MSG_LIST_SUC = 'FETCH_MSG_LIST_SUC'
export const FETCH_MSG_LIST_ERR = 'FETCH_MSG_LIST_ERR'
export const CLEAR_MSG_LIST_DATA = 'CLEAR_MSG_LIST_DATA'

// contact
export const FETCH_CONTACT_REQ = 'FETCH_CONTACT_REQ'
export const FETCH_CONTACT_SUC = 'FETCH_CONTACT_SUC'
export const FETCH_CONTACT_ERR = 'FETCH_CONTACT_ERR'
export const CLEAR_CONTACT_DATA = 'CLEAR_CONTACT_DATA'

//moments
export const FETCH_MOMENTS_REQ = 'FETCH_MOMENTS_REQ'
export const FETCH_MOMENTS_SUC = 'FETCH_MOMENTS_SUC'
export const FETCH_MOMENTS_ERR = 'FETCH_MOMENTS_ERR'
export const CLEAR_MOMENTS_DATA = 'CLEAR_MOMENTS_DATA'

//resource
export const FETCH_RESOURCE_REQ = 'FETCH_RESOURCE_REQ'
export const FETCH_RESOURCE_SUC = 'FETCH_RESOURCE_SUC'
export const FETCH_RESOURCE_ERR = 'FETCH_RESOURCE_ERR'
export const CLEAR_RESOURCE_DATA = 'CLEAR_RESOURCE_DATA'

//resourcelist
export const FETCH_RESOURCE_LIST_REQ = 'FETCH_RESOURCE_LIST_REQ'
export const FETCH_RESOURCE_LIST_SUC = 'FETCH_RESOURCE_LIST_SUC'
export const FETCH_RESOURCE_LIST_ERR = 'FETCH_RESOURCE_LIST_ERR'
export const CLEAR_RESOURCE_LIST_DATA = 'CLEAR_RESOURCE_LIST_DATA'

//resourcedetail
export const FETCH_RESOURCE_DETAIL_REQ = 'FETCH_RESOURCE_DETAIL_REQ'
export const FETCH_RESOURCE_DETAIL_SUC = 'FETCH_RESOURCE_DETAIL_SUC'
export const FETCH_RESOURCE_DETAIL_ERR = 'FETCH_RESOURCE_DETAIL_ERR'
export const CLEAR_RESOURCE_DETAIL_DATA = 'CLEAR_RESOURCE_DETAIL_DATA'
export const GETTER_RESOURCE_DETAIL_DATA='GETTER_RESOURCE_DETAIL_DATA'

// release
export const SHOW_RELEASE_PAGE = 'SHOW_RELEASE_PAGE'
export const HIDE_RELEASE_PAGE = 'HIDE_RELEASE_PAGE'
export const FETCH_RELEASE_REQ = 'FETCH_RELEASE_REQ'
export const FETCH_RELEASE_SUC = 'FETCH_RELEASE_SUC'
export const FETCH_RELEASE_ERR = 'FETCH_RELEASE_ERR'

//activity
export const FETCH_ACTIVITY_REQ = 'FETCH_ACTIVITY_REQ'
export const FETCH_ACTIVITY_SUC = 'FETCH_ACTIVITY_SUC'
export const FETCH_ACTIVITY_ERR = 'FETCH_ACTIVITY_ERR'
export const CLEAR_ACTIVITY_DATA = 'CLEAR_ACTIVITY_DATA'

//moments-activity
export const FETCH_MOMENTS_ACTIVITY_REQ = 'FETCH_MOMENTS_ACTIVITY_REQ'
export const FETCH_MOMENTS_ACTIVITY_SUC = 'FETCH_MOMENTS_ACTIVITY_SUC'
export const FETCH_MOMENTS_ACTIVITY_ERR = 'FETCH_MOMENTS_ACTIVITY_ERR'
export const CLEAR_MOMENTS_ACTIVITY_DATA = 'CLEAR_MOMENTS_ACTIVITY_DATA'

//frienddetail
export const FETCH_FRIEND_DETAIL_REQ = 'FETCH_FRIEND_DETAIL_REQ'
export const FETCH_FRIEND_DETAIL_SUC = 'FETCH_FRIEND_DETAIL_SUC'
export const FETCH_FRIEND_DETAIL_ERR = 'FETCH_FRIEND_DETAIL_ERR'
export const CLEAR_FRIEND_DETAIL_DATA = 'CLEAR_FRIEND_DETAIL_DATA'
export const GETTER_FRIEND_DETAIL_USER='GETTER_FRIEND_DETAIL_USER'
export const GETTER_FRIEND_DETAIL='GETTER_FRIEND_DETAIL'
/**
 * Common
 * @param {refresh}
 * @param {dialog}
 * @param {snack}
 * @param {main page overflow}
 * @param {bottomnav}
 */
// refresh
export const SHOW_REFRESH = 'SHOW_REFRESH'
export const HIDE_REFRESH = 'HIDE_REFRESH'

// snackbar
export const SHOW_SNACK = 'SHOW_SNACK'
export const HIDE_SNACK = 'HIDE_SNACK'
export const DEFINE_SNACK_MSG = 'DEFINE_SNACK_MSG'
export const DEFINE_SNACK_TYPE = 'DEFINE_SNACK_TYPE'
export const DEFINE_SNACK_POSITION = 'DEFINE_SNACK_POSITION'

// dialog
export const SHOW_TIP_DIALOG = 'SHOW_TIP_DIALOG'
export const HIDE_TIP_DIALOG = 'HIDE_TIP_DIALOG'

// bottom nav
export const HANDLE_CHANGE = 'HANDLE_CHANGE'

// main overflow
export const SHOW_MAIN_OVERFLOW = 'SHOW_MAIN_OVERFLOW'
export const HIDE_MAIN_OVERFLOW = 'HIDE_MAIN_OVERFLOW'

/*********** mutations ***********/

/*********** Getters ***********/
// login
export const COLLECTS_COUNT = 'COLLECTS_COUNT'
export const REPLIES_COUNT = 'REPLIES_COUNT'
export const MY_TOPICS_COUNT = 'MY_TOPICS_COUNT'

// message
export const HAS_NOT_READ_MESSAGES_COUNT = 'HAS_NOT_READ_MESSAGES_COUNT'
	/*********** getters ***********/